name: Bug Report
description: Report a bug or unexpected behavior
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report this bug! Please fill out the form below.

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: Describe the bug...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: I expected...
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happened?
      placeholder: Instead, what happened was...
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true

  - type: dropdown
    id: area
    attributes:
      label: Area Affected
      description: Which part of the application is affected?
      options:
        - Authentication / Login
        - Tool Management
        - Reservations / Booking
        - Calendar
        - Search
        - Circles / Groups
        - Notifications
        - Subscription / Billing
        - Photos / Images
        - Profile
        - API
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical - System unusable
        - High - Major feature broken
        - Medium - Feature impaired but workaround exists
        - Low - Minor issue
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Relevant Logs / Screenshots
      description: Add any relevant logs, error messages, or screenshots
      placeholder: Paste logs or drag and drop screenshots here...

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide environment details
      placeholder: |
        - Browser: Chrome 120
        - OS: Windows 11
        - Device: Desktop
        - Environment: Production / UAT / Dev
