name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the current pain point?
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: I would like...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Have you considered any alternative solutions or workarounds?
      placeholder: I've also considered...

  - type: dropdown
    id: area
    attributes:
      label: Area Affected
      description: Which part of the application would this affect?
      options:
        - Authentication / Login
        - Tool Management
        - Reservations / Booking
        - Calendar
        - Search
        - Circles / Groups
        - Notifications
        - Subscription / Billing
        - Photos / Images
        - Profile
        - API
        - New Area
        - Other
    validations:
      required: true

  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: Who would benefit from this feature?
      options:
        - All Users
        - Tool Owners (Lenders)
        - Borrowers
        - Circle Admins
        - System Admins
    validations:
      required: true

  - type: textarea
    id: acceptance-criteria
    attributes:
      label: Acceptance Criteria
      description: How would we know this feature is complete?
      placeholder: |
        - [ ] User can...
        - [ ] System should...

  - type: textarea
    id: context
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots
      placeholder: Drag and drop images or add additional details...
